# Generated by Django 4.1.4 on 2023-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_vehicle', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('handled', models.BooleanField(default=False)),
                ('imag', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
