# Generated by Django 4.2 on 2023-05-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='imag',
        ),
        migrations.AddField(
            model_name='accident',
            name='title',
            field=models.CharField(default='accident ', max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('danger', 'Danger'), ('deadly', 'Deadly')], max_length=50),
        ),
        migrations.CreateModel(
            name='AccidentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='road.accident')),
            ],
        ),
    ]
