# Generated by Django 4.2 on 2023-05-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_remove_accident_imag_accident_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='road',
        ),
    ]
