# Generated by Django 4.2 on 2023-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_remove_accident_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='description',
            field=models.TextField(default='this is a Accident'),
        ),
    ]
