# Generated by Django 4.1.4 on 2023-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_vehicle', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('handled', models.BooleanField(default=False)),
            ],
        ),
    ]
