# Generated by Django 4.1.4 on 2023-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
